### ISSUE TITLE
Configure condor to use UDP for collector updates

### ISSUE THREAD

**Issue by vbrik** [WIPACrepo/pyglidein#100]
Wed May 03 10:41:55 2017 (?)

[9:47 AM] ￼
David Schultz we currently use TCP with pyglidein. maybe we should try UDP? that would scale better, though it might not go through every site firewall

[10:02 AM] ￼
Gonzalo Merino sounds like we should try

[10:39 AM] ￼
Vladimir Brik Worth a try, but I wonder what effect our sometimes-strained firewall will have on UDP. The worry of course that there will be massive drops, but might actually lower the load by reducing amount of state processing required for tcp connections.

[10:41 AM] ￼
Another thing I was thinking about is using UDP when submitters talk to glidein-simprod, but I don't know if it can be configured at that level of granularity.

[10:41 AM] ￼
Anyhow, I'll create a ticket.

**Comment by dsschult** [comment]
closed as wontfix for now
