### ISSUE TITLE
Update Install instructions for 2.6 users

### ISSUE THREAD

**Issue by hskarlupka** [WIPACrepo/pyglidein#124]
Setuptools stopped supporting python 2.6 in v37.  Update install docs with a CentOS 6 section to tell people to:
`pip install setuptools==36.8.0` 
before installing pyglidein.

**Comment by hugovk** [comment]
Do you still need to support Python 2.6? It's EOL, hasn't received security updates in 4 years and generally has low use.

Here's monthly pip installs from PyPI (via `pypinfo --percent --pip --markdown "" pyversion`)

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   77.7% |    435,636,261 |
| 3.6            |    8.8% |     49,199,570 |
| 3.5            |    8.4% |     46,927,461 |
| 3.4            |    3.9% |     21,843,444 |
| 2.6            |    1.1% |      6,194,026 |
| 3.3            |    0.1% |        554,661 |
| 3.7            |    0.1% |        428,159 |
| 3.2            |    0.0% |         38,570 |
| None           |    0.0% |         21,921 |
| 2.8            |    0.0% |             35 |
| 3.1            |    0.0% |             26 |

**Comment by dsschult** [comment]
Yes, because RHEL6 runs python 2.6.  Unfortunately, it still is the most popular OS on clusters.

**Comment by hskarlupka** [comment]
Updated Install Readme.
