### ISSUE TITLE
CLSIM Benchmark Fails on RHEL6 Pyglidein Nodes

### ISSUE THREAD

**Issue by hskarlupka** [WIPACrepo/pyglidein#141]
The CLSIM benchmarks fails on RHEL6 nodes with unknown errors.  It would be good to have the error output written into the classad instead of "False".  This will help us debug the issues.

**Comment by gonzalomerino** [comment]
Hi,

This is a good idea

but I am curious to see how clsim fails in RHEL6. We are running this in
RHEL6 in many sites, since a long time ago. This must be some specific
problem with Comet config, their drivers, opencl or who knows what.. right?

**Comment by hskarlupka** [comment]
@gonzalomerino Good question.  David and I didn't see anything obvious wrong with the clsim benchmark check script I wrote.  I wrote the code to get the error into the classad and updated pyglidein on comet.  We will know more in the next couple of days as we start looking at the log output.

**Comment by hskarlupka** [comment]
I submitted the clsim test script as a condor job and it returned successfully.  I'll put condor in full debug mode at one of the sites.

**Comment by hskarlupka** [comment]
From Comet: 

`02/20/18 06:52:59 clsimgpu: ../../post_cvmfs.sh: line 3: /cvmfs/icecube.opensciencegrid.org/py2-v2/setup.sh: No such file or directory`

**Comment by hskarlupka** [comment]
I've tried every which way to run this inside a parrot wrapper, but have failed.  Any site without /cvmfs is not going to work.

**Comment by hskarlupka** [comment]
Debugging this on gtx and gzk now.

**Comment by hskarlupka** [comment]
https://github.com/WIPACrepo/pyglidein/pull/147
