### ISSUE TITLE
New Machine ClassAd to store the "pyglidein factory" site name 

### ISSUE THREAD

**Issue by gonzalomerino** [WIPACrepo/pyglidein#37]
It will be nice to have a new ClassAd that contains the pyglidein factory site name, like for instance:

GLIDEIN_pyGlideinSite = NPX

Now we are already filling in this information in the "standard" GLIDEIN_Site ClassAd. But it will be good to have a new one so that wherever we run pyglideins inside OSG glideins we can keep the information of both the executing site and the pyGlidein Factory.

So for most of the pyGlidein sites where we have a one-to-one Factory to Site this will be always:

GLIDEIN_pyGlideinSite = GLIDEIN_Site

But for sites that submit to glidein pools, these will be different like for instance:

GLIDEIN_pyGlideinSite = osgconnect
GLIDEIN_Site = DESY-HH

The pyglidein will need to discover at startup that it is running inside an (OSG) glidein, and if that is the case, "inherit" all the existing GLIDEIN_\* variables to preserve that information in the pyglidein.

**Comment by dsschult** [comment]
The name "GLIDEIN_pyGlideinSite" just looks strange to me.  How about "GLIDEIN_Submitter"?  Or maybe "PYGLIDEIN_Site"?

**Comment by briedel** [comment]
Are we planning on having more than queue that we submit glideins from or am I misunderstanding something?

**Comment by dsschult** [comment]
I meant the remote submitter.  Where the glidein itself is submitted, not the user jobs.
