### ISSUE TITLE
default slot environment

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/pyglidein#47]
Currently we load `/cvmfs/icecube.opensciencegrid.org/py2-v1/setup.sh` before starting a job.  This is bad when running any other environment.  Figure out how to put this into an option, or just disable it entirely.

(note that it's handy when running iceprod1, as it correctly finds opencl. but not useful for anyone else)

**Comment by briedel** [comment]
condor classes specifying the cvmfs version?

**Comment by jvansanten** [comment]
That's not a bad idea, but it would be nice if there were a pattern to
follow (a la OpSyS).

**Comment by dsschult** [comment]
Option to disable as of 5152143.  We should think of making this the default now that iceprod v1 is winding down.
