### ISSUE TITLE
Mechanism to "pass" some of the Machine ClassAds as Job ClassAds for the pyglidein jobs

### ISSUE THREAD

**Issue by gonzalomerino** [WIPACrepo/pyglidein#59]
I think it would be  nice if we could have some of the Machine ClassAds that we publish (such as GLIDEIN_Site for instance) somehow passed to the Job, so that we could keep record of them in the condor history (job accounting).

Another use for this would be the possible future GLIDEIN_GpuType (see #60)

**Comment by dsschult** [comment]
I think we're looking for `SYSTEM_JOB_MACHINE_ATTRS`.

The gpu detection sounds like a separate ticket.

**Comment by dsschult** [comment]
I think `SYSTEM_JOB_MACHINE_ATTRS` doesn't work on the startd.  Probably needs to be on the schedd.

Also, I notice that you already have something like this deployed on `sub-simprod` at least:
```
MATCH_EXP_JOBGLIDEIN_ResourceName = "NPX"
JOBGLIDEIN_ResourceName = "$$([IfThenElse(IsUndefined(TARGET.GLIDEIN_ResourceName), IfThenElse(IsUndefined(TARGET.GLIDEIN_Site), IfThenElse(IsUndefined(TARGET.FileSystemDomain), \"Local Job\", TARGET.FileSystemDomain), TARGET.GLIDEIN_Site), TARGET.GLIDEIN_ResourceName)])"
```

**Comment by dsschult** [comment]
I poked around the condor manual again, and I think you can't do this from the startd.  Probably because of security, since injecting GB worth of classads could cripple a scheduler.

So I'm going to have to mark this as WONTFIX.

**Comment by vbrik** [comment]
As David said, this has to be done on the submitter. The preferred way to do this is the following (note you have to use `JobMachineAttrs`):

    SUBMIT_ATTRS = $(SUBMIT_ATTRS) JobMachineAttrs
    JobMachineAttrs = "Mips JavaMFlops"

The following will also work, but Condor devs discourage this approach because failing to preserved default `SYSTEM_JOB_MACHINE_ATTRS` will break Condor

    SYSTEM_JOB_MACHINE_ATTRS = $(SYSTEM_JOB_MACHINE_ATTRS),Mips,JavaMFlops

The attributes saved in job ad in this case will be called `MachineAttrMips0` and `MachineAttrJavaMFlops0`. The trailing number (0 in this case) is used to index values if job had been restarted. The number of values preserved is controlled by `SYSTEM_JOB_MACHINE_ATTRS_HISTORY_LENGTH`.

If SUBMIT_ATTRS approach is used, `JobMachineAttrs` attribute will also be saved (`JobMachineAttrs = "Mips JavaMFlops"`)

**Comment by gonzalomerino** [comment]
Recapitulating on discussions we had on this thread some months ago, if we look at getting the "site" information in the job classads, David pointed out that we are actually already doing that via this gratia configuration file.

```
sub-1 ~ # cat /etc/condor/config.d/99_gratia.conf 
# This file is from the gratia-probe-condor rpm.
# It will put history.* files into the gratia data directory
# in order for gratia to submit usage.

PER_JOB_HISTORY_DIR = /var/lib/gratia/data
JOBGLIDEIN_ResourceName="$$([IfThenElse(IsUndefined(TARGET.GLIDEIN_ResourceName), IfThenElse(IsUndefined(TARGET.GLIDEIN_Site), \"Local Job\", TARGET.GLIDEIN_Site), TARGET.GLIDEIN_ResourceName)])"
SUBMIT_EXPRS = $(SUBMIT_EXPRS) JOBGLIDEIN_ResourceName
```
This is probably how we get the `MATCH_EXP_JOBGLIDEIN_ResourceName` classad that we then use in kibana or grafana to get info on the site where the job ran.

```
sub-1 ~ # condor_history -long -limit 1 | grep GLIDEIN_ResourceName
MATCH_EXP_JOBGLIDEIN_ResourceName = "NPX"
JOBGLIDEIN_ResourceName = "$$([IfThenElse(IsUndefined(TARGET.GLIDEIN_ResourceName), IfThenElse(IsUndefined(TARGET.GLIDEIN_Site), \"Local Job\", TARGET.GLIDEIN_Site), TARGET.GLIDEIN_ResourceName)])"
```

This gratia config uses this same mechanism that Vlad just described yesterday. Apparently, SUBMIT_ATTRS is just the new way to do SUBMIT_EXPRS, otherwise they are the same thing.

Now in our pyglidein we pass our client.py "Site" information inside the GLIDEIN_Site classAd, and this is how we eventually get it in MATCH_EXP_JOBGLIDEIN_ResourceName.

for the sites for which the client.py submit site is not giving us info on the execution site (for instance, xsede-osg, or osgconnect) it might be good to have some way to get that information and add some code to our pyglidein that tries to "discover" the site where the glidein is actually running. 

We could do a 

```
curl -s http://simprod.icecube.wisc.edu/downloads/getip.php
```

in the glidein, and then resolve the IP to domainname ... or something like this.

thoughts?

**Comment by dsschult** [comment]
That's ticket #80.  And it's much easier than that, since we can grab the info from the OSG glidein we run inside.

**Comment by briedel** [comment]
For OSG Connect and XSede-OSG, the OSG glideins should provide the site name in the environment (`$OSG_SITE_NAME`).

**Comment by gonzalomerino** [comment]
David, following up on your last comment: you're right that for the sites that we need this (xsede-osg and osgconnect) we end up running inside OSG glideins therefore they already should be filling in this information in GLIDEIN_ResourceName.

What we are currently doing is probably overwriting GLIDEIN_ResourceName with "xsede-osg" for instance, so we lose whatever information the OSG glidein could pass to us on the execution site. Should we write our pyglidein Site information in GLIDEIN_Site instead, and add it to SUBMIT_EXPRS in the submitters so that we keep both GLIDEIN_Site and GLIDEIN_ResourceName in the condor_history?

**Comment by gonzalomerino** [comment]
Disregard my previous message... I see that what we do is actually to fill in the pyglidein Site info inside GLIDEIN_Site.

So what is missing is to somehow "pass" whatever info OSG has for the execution site into GLIDEIN_ResourceName. That is probably what Benedikt was pointing to with `$OSG_SITE_NAME`
