### ISSUE TITLE
work with containers

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/pyglidein#62]
Containers are a thing now.  NERSC requires them, and I wouldn't be surprised for other sites to follow along.

So, figure out the correct way to submit a glidein inside a container.  Mostly it's documentation with an example, but there might be issues with the wrapper script or `glidein_start.sh`.

**Comment by dsschult** [comment]
From NERSC:

Found an issue with HTCondor: 
```
01/10/17 12:54:37 my_popenv failed
01/10/17 12:54:37 ERROR "fopen of "/var/run/utmp"" at line 273 in file /home/dschultz/pyglidein/tmp15Mj7h/htcondor-8_4_2/src/condor_sysapi/idle_time.cpp
```

Apparently we can't map anything in `/var` into the container for security reasons.

**Comment by briedel** [comment]
Is that setting from within condor or something we set? We are running a small CoreOS based test cluster using HTCondor without that issue.

**Comment by dsschult** [comment]
I bet there's a way to turn it off, but we might need to find the right knob.  Probably the one to monitor user activity and treat like a workstation that might go back to the user.

**Comment by dsschult** [comment]
The setting `STARTD_HAS_BAD_UTMP = TRUE` might do it.

**Comment by dsschult** [comment]
As noted on #9, we need to fix `os_arch.sh` to run on docker.

**Comment by dsschult** [comment]
95e326d fixes `os_arch.sh`

**Comment by hskarlupka** [comment]
Submit jobs via Shifter

**Comment by dsschult** [comment]
closing this ticket in favor of #106, as that's more detailed to the issue.
