### ISSUE TITLE
Adding glideins_queued to the client monitoring info displayed in the server

### ISSUE THREAD

**Issue by gonzalomerino** [WIPACrepo/pyglidein#67]
Now the server web page displays information for each client's glideins_running and glideins_launched.

It would be nice to add glideins_queued to that  information.

**Comment by dsschult** [comment]
Need to restructure how clients read the local queue, to separate out queued and processing jobs.

**Comment by jvansanten** [comment]
The client knows how many of the jobs are idle if you provide an `idle_cmd`. Otherwise, it considers all jobs in the queue to be "running."

**Comment by gonzalomerino** [comment]
This was done by Heath in another ticket (#110)
