### ISSUE TITLE
condor 8.6 and auth

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/pyglidein#74]
Apparently condor 8.6 changed something that broke our password authentication.  Test this more thoroughly before deploying.

**Comment by vbrik** [comment]
When updating glidein-simprod to 8.5.8 (probably from 8.3.8), I had to change mode of the password file from 660 to 600. I don't remember what exactly broke though.

**Comment by dsschult** [comment]
Note that apparently I had the right permissions (600) in my local copy, but git doesn't save permissions.

**Comment by dsschult** [comment]
Another issue was the glidein trying to use SHARED_PORT.  Turning that off makes it work in testing.
