### ISSUE TITLE
figure out why monitoring is flapping

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/pyglidein#88]
The site monitoring for slack is flapping a lot (going up and down about once a day).  Since no user intervention is taking place, things must be working OK.

Maybe the client isn't reporting monitoring information when nothing is queued?

**Comment by jvansanten** [comment]
The client appears to report monitoring info [https://github.com/WIPACrepo/pyglidein/blob/master/client.py#L183](unconditionally). Maybe the affected sites are running on a weird cron schedule?

The two times that the bot warning has triggered for the Zeuthen site have been real failures where the batch system went down temporarily, and submissions began to fail, taking down the client.

**Comment by dsschult** [comment]
So this disappeared.  Not sure if that means monitoring is broken, but this goes away.
