### ISSUE TITLE
Support multiple OS types

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/pyglidein#9]
Glideins are built to an OS (more accurately, to a version of libc and other libraries).  At some point we need to support multiple OS types, detecting which one on startup and downloading the appropriate glidein tarball.

**Comment by dsschult** [comment]
Bridges (PSC) needs this.  Currently using a local tarball for CentOS 7.

**Comment by dsschult** [comment]
OSG is starting to get RHEL7 nodes.  We need this to be fixed soon.  Any volunteers? (hint: @jvansanten)

**Comment by briedel** [comment]
Just a note.... if that is the `os_arch.sh` from cvmfs. It will break when using docker, the last time i tested it

**Comment by dsschult** [comment]
Ah, right.  Still need to fix that.

note for #62
